2024-12-02 13:43:26,454 - srv.conf.config - ERROR - Section PG not found in config.ini
2024-12-02 13:43:26,454 - srv.conf.config - ERROR - Failed to create DB URL: Section PG not found in config.ini
2024-12-02 13:47:21,965 - srv.conf.config - ERROR - Section PG not found in config.ini
2024-12-02 13:47:21,966 - srv.conf.config - ERROR - Failed to create DB URL: Section PG not found in config.ini
2024-12-02 13:47:32,020 - srv.conf.config - ERROR - Section PG not found in config.ini
2024-12-02 13:47:32,020 - srv.conf.config - ERROR - Failed to create DB URL: Section PG not found in config.ini
2024-12-06 18:53:12,846 - srv.conf.config - ERROR - Failed to load ALGORITHM: 'algorithm'
2024-12-06 19:20:18,277 - srv.database.db - ERROR - Session rollback due to exception: 401: invalid email
2024-12-06 19:43:20,618 - srv.database.db - ERROR - Session rollback due to exception: 401: invalid email
2024-12-06 19:43:32,862 - srv.database.db - ERROR - Session rollback due to exception: 401: invalid email
2024-12-06 19:45:19,870 - srv.database.db - ERROR - Session rollback due to exception: 401: Invalid refresh token
2024-12-06 19:46:12,891 - srv.database.db - ERROR - Session rollback due to exception: 401: Invalid refresh token
2024-12-06 20:12:58,051 - srv.database.db - ERROR - Session rollback due to exception: 401: Not authenticated
2024-12-06 20:41:31,775 - srv.database.db - ERROR - Session rollback due to exception: 401: Could not validate credentials
2024-12-06 20:44:33,900 - srv.database.db - ERROR - Session rollback due to exception: 'user_id' is an invalid keyword argument for Contact
2024-12-10 11:54:40,430 - srv.conf.config - ERROR - Failed to load mail serves configuration: 'host'
2024-12-10 12:10:48,689 - srv.database.db - ERROR - Session rollback due to exception: 409: Account already exists
2024-12-10 12:15:36,337 - srv.services.email - ERROR - Exception raised Error connecting to smtp.meta.com on port 465: [Errno 8] nodename nor servname provided, or not known, check your credentials or email service configuration
2024-12-10 12:16:47,187 - srv.services.email - ERROR - Exception raised Error connecting to smtp.meta.com on port 465: [Errno 8] nodename nor servname provided, or not known, check your credentials or email service configuration
2024-12-10 12:23:28,329 - srv.services.email - ERROR - Exception raised Error connecting to smtp.meta.com on port 465: [Errno 8] nodename nor servname provided, or not known, check your credentials or email service configuration
2024-12-10 12:30:05,369 - srv.database.db - ERROR - Session rollback due to exception: 409: Account already exists
2024-12-10 12:30:26,752 - srv.services.email - ERROR - Exception raised Error connecting to smtp.meta.com on port 465: [Errno 8] nodename nor servname provided, or not known, check your credentials or email service configuration
2024-12-10 12:34:06,386 - srv.database.db - ERROR - Session rollback due to exception: 'Depends' object has no attribute 'execute'
2024-12-10 12:36:42,785 - srv.database.db - ERROR - Session rollback due to exception: 'Depends' object has no attribute 'execute'
2024-12-10 14:26:35,884 - srv.database.db - ERROR - Session rollback due to exception: 409: Account already exists
2024-12-10 18:30:50,360 - srv.conf.conn_rabbitMQ - INFO - Successfully connected to RabbitMQ
2024-12-10 18:31:17,391 - srv.conf.conn_rabbitMQ - INFO - Successfully connected to RabbitMQ
2024-12-10 18:32:54,842 - srv.conf.conn_rabbitMQ - INFO - Successfully connected to RabbitMQ
2024-12-10 18:54:58,349 - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-10 21:32:54,759 - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-10 21:32:54,770 - global_logger - INFO - Worker is consuming messages...
2024-12-10 21:43:34,796 - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-10 21:43:36,662 - global_logger - INFO - Message precessed successfully : gesipew657@eoilup.com
2024-12-10 22:05:21,236 - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-10 22:05:21,243 - global_logger - INFO - Worker is consuming messages...
2024-12-11 11:48:51,389 - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-11 11:48:51,395 - global_logger - INFO - Worker is consuming messages...
2024-12-11 11:51:15,769 - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-11 11:51:17,684 - global_logger - INFO - Message precessed successfully : gesipew657@eoilup.com
2024-12-11 11:55:05,031 - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-11 11:55:06,852 - global_logger - INFO - Message precessed successfully : gesipew657@eoilup.com
2024-12-11 11:55:26,945 - global_logger - INFO - string open link
2024-12-11 12:04:14,328 - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-11 12:04:16,176 - global_logger - INFO - Message precessed successfully : xoyemi9795@datingel.com
2024-12-11 12:07:31,007 - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-11 12:07:32,626 - global_logger - INFO - Message precessed successfully : xoyemi9795@datingel.com
2024-12-11 12:09:12,137 - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-11 12:09:13,695 - global_logger - INFO - Message precessed successfully : xoyemi9795@datingel.com
2024-12-11 12:10:55,184 - global_logger - INFO - Dima open link
2024-12-11 12:32:29,022 - global_logger - INFO - dima open link
2024-12-11 16:25:12,824 - check_open.py - global_logger - INFO - Dima open link
2024-12-11 16:36:56,558 - users.py - global_logger - INFO - Request to /me endpoint
2024-12-12 14:24:22,416 - auth.py - global_logger - INFO - User gesipew657@eoilup.com from cache
2024-12-12 14:24:22,424 - users.py - global_logger - INFO - Request to /me endpoint
2024-12-12 18:05:57,309 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 18:06:59,692 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 18:06:59,700 - rabbitmq_worker.py - global_logger - INFO - Worker is consuming messages...
2024-12-12 18:07:05,924 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 18:07:06,892 - rabbitmq_worker.py - global_logger - INFO - Message precessed successfully : xoyemi9795@datingel.com. Type: email_verification
2024-12-12 18:11:39,134 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 18:11:39,138 - mail_publisher.py - global_logger - INFO - Message published to RabbitMQ with routing_key 'reset_password': {'email': 'xoyemi9795@datingel.com', 'username': 'string', 'host': 'http://127.0.0.1:8000/', 'type': 'reset_password'}
2024-12-12 18:11:39,988 - rabbitmq_worker.py - global_logger - ERROR - Failed to process message: (550, 'Message subject: SPAM FOUND')
2024-12-12 18:12:52,364 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 18:12:52,372 - rabbitmq_worker.py - global_logger - INFO - Worker is consuming messages...
2024-12-12 18:13:05,981 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 18:13:05,990 - mail_publisher.py - global_logger - INFO - Message published to RabbitMQ with routing_key 'reset_password': {'email': 'xoyemi9795@datingel.com', 'username': 'string', 'host': 'http://127.0.0.1:8000/', 'type': 'reset_password'}
2024-12-12 18:13:06,837 - rabbitmq_worker.py - global_logger - ERROR - Failed to process message: (550, 'Message subject: SPAM FOUND')
2024-12-12 18:16:04,143 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 18:16:04,148 - rabbitmq_worker.py - global_logger - INFO - Worker is consuming messages...
2024-12-12 18:16:43,066 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 18:16:43,071 - mail_publisher.py - global_logger - INFO - Message published to RabbitMQ with routing_key 'reset_password': {'email': 'xoyemi9795@datingel.com', 'username': 'string', 'host': 'http://127.0.0.1:8000/', 'type': 'reset_password'}
2024-12-12 18:16:43,933 - rabbitmq_worker.py - global_logger - ERROR - Failed to process message: (550, 'Message subject: SPAM FOUND')
2024-12-12 18:18:58,856 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 18:18:58,865 - mail_publisher.py - global_logger - INFO - Message published to RabbitMQ with routing_key 'reset_password': {'email': 'xoyemi9795@datingel.com', 'username': 'string', 'host': 'http://127.0.0.1:8000/', 'type': 'reset_password'}
2024-12-12 18:18:59,716 - rabbitmq_worker.py - global_logger - ERROR - Failed to process message: (550, 'Message subject: SPAM FOUND')
2024-12-12 18:19:32,555 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 18:19:32,570 - mail_publisher.py - global_logger - INFO - Message published to RabbitMQ with routing_key 'reset_password': {'email': 'xoyemi9795@datingel.com', 'username': 'string', 'host': 'http://127.0.0.1:8000/', 'type': 'reset_password'}
2024-12-12 18:19:38,748 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 18:19:38,752 - rabbitmq_worker.py - global_logger - INFO - Worker is consuming messages...
2024-12-12 18:19:39,632 - rabbitmq_worker.py - global_logger - ERROR - Failed to process message: (550, 'Message subject: SPAM FOUND')
2024-12-12 18:20:26,254 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 18:20:26,261 - rabbitmq_worker.py - global_logger - INFO - Worker is consuming messages...
2024-12-12 18:20:31,737 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 18:20:31,743 - mail_publisher.py - global_logger - INFO - Message published to RabbitMQ with routing_key 'reset_password': {'email': 'xoyemi9795@datingel.com', 'username': 'string', 'host': 'http://127.0.0.1:8000/', 'type': 'reset_password'}
2024-12-12 18:20:32,587 - rabbitmq_worker.py - global_logger - ERROR - Failed to process message: (550, 'Message subject: SPAM FOUND')
2024-12-12 18:27:20,558 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 18:27:20,563 - rabbitmq_worker.py - global_logger - INFO - Worker is consuming messages...
2024-12-12 18:27:26,223 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 18:27:26,229 - mail_publisher.py - global_logger - INFO - Message published to RabbitMQ with routing_key 'reset_password': {'email': 'xoyemi9795@datingel.com', 'username': 'string', 'host': 'http://127.0.0.1:8000/', 'type': 'reset_password'}
2024-12-12 18:27:27,096 - rabbitmq_worker.py - global_logger - ERROR - Failed to process message: (550, 'Message subject: SPAM FOUND')
2024-12-12 18:28:34,953 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 18:28:34,958 - rabbitmq_worker.py - global_logger - INFO - Worker is consuming messages...
2024-12-12 18:28:40,350 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 18:28:40,357 - mail_publisher.py - global_logger - INFO - Message published to RabbitMQ with routing_key 'reset_password': {'email': 'xoyemi9795@datingel.com', 'username': 'string', 'host': 'http://127.0.0.1:8000/', 'type': 'reset_password'}
2024-12-12 18:28:41,209 - rabbitmq_worker.py - global_logger - ERROR - Failed to process message: (550, 'Message subject: SPAM FOUND')
2024-12-12 18:29:04,717 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 18:29:04,722 - rabbitmq_worker.py - global_logger - INFO - Worker is consuming messages...
2024-12-12 18:29:08,251 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 18:29:08,258 - mail_publisher.py - global_logger - INFO - Message published to RabbitMQ with routing_key 'reset_password': {'email': 'xoyemi9795@datingel.com', 'username': 'string', 'host': 'http://127.0.0.1:8000/', 'type': 'reset_password'}
2024-12-12 18:29:09,111 - rabbitmq_worker.py - global_logger - ERROR - Failed to process message: (550, 'Message subject: SPAM FOUND')
2024-12-12 18:30:02,601 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 18:30:02,608 - rabbitmq_worker.py - global_logger - INFO - Worker is consuming messages...
2024-12-12 18:30:41,781 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 18:30:41,787 - mail_publisher.py - global_logger - INFO - Message published to RabbitMQ with routing_key 'email_verification': {'email': 'xoyemi9795@datingel.com', 'username': 'string', 'host': 'http://127.0.0.1:8000/', 'type': 'email_verification'}
2024-12-12 18:30:42,633 - rabbitmq_worker.py - global_logger - INFO - Message precessed successfully : xoyemi9795@datingel.com. Type: email_verification
2024-12-12 19:12:29,670 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 19:12:29,676 - rabbitmq_worker.py - global_logger - INFO - Worker is consuming messages...
2024-12-12 19:12:35,159 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 19:12:35,163 - mail_publisher.py - global_logger - INFO - Message published to RabbitMQ with routing_key 'reset_password': {'email': 'xoyemi9795@datingel.com', 'username': 'string', 'host': 'http://127.0.0.1:8000/', 'type': 'reset_password'}
2024-12-12 19:12:36,018 - rabbitmq_worker.py - global_logger - ERROR - Failed to process message: (550, 'Message subject: SPAM FOUND')
2024-12-12 21:47:36,874 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 21:47:36,880 - rabbitmq_worker.py - global_logger - INFO - Worker is consuming messages...
2024-12-12 21:48:29,360 - db.py - global_logger - ERROR - Session rollback due to exception: 401: Not confirmed email
2024-12-12 21:49:27,663 - db.py - global_logger - ERROR - Session rollback due to exception: 'str' object has no attribute 'copy'
2024-12-12 21:52:11,202 - db.py - global_logger - ERROR - Session rollback due to exception: 'str' object has no attribute 'copy'
2024-12-12 21:57:16,177 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 21:57:16,182 - rabbitmq_worker.py - global_logger - INFO - Worker is consuming messages...
2024-12-12 21:57:22,057 - db.py - global_logger - ERROR - Session rollback due to exception: 'User' object has no attribute 'copy'
2024-12-12 22:00:57,184 - db.py - global_logger - ERROR - Session rollback due to exception: Object of type InstanceState is not JSON serializable
2024-12-12 22:09:43,263 - db.py - global_logger - ERROR - Session rollback due to exception: 'User' object has no attribute 'dict'
2024-12-12 22:10:55,942 - db.py - global_logger - ERROR - Session rollback due to exception: 'User' object is not iterable
2024-12-12 22:16:53,237 - db.py - global_logger - ERROR - Session rollback due to exception: object str can't be used in 'await' expression
2024-12-12 22:29:44,710 - db.py - global_logger - ERROR - Session rollback due to exception: object str can't be used in 'await' expression
2024-12-12 22:32:07,253 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 22:32:07,260 - mail_publisher.py - global_logger - INFO - Message published to RabbitMQ with routing_key 'email_verification': {'email': 'xoyemi9795@datingel.com', 'username': 'string', 'host': 'http://127.0.0.1:8000/', 'type': 'email_verification', 'verification_token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ4b3llbWk5Nzk1QGRhdGluZ2VsLmNvbSIsImlhdCI6MTczNDAzNTUyNywiZXhwIjoxNzM0NjQwMzI3fQ._oMMEWa1LLF2X7Ulo2HQ6uz2kw9ARkLzqJUAO2t34js'}
2024-12-12 22:32:08,219 - rabbitmq_worker.py - global_logger - INFO - Message precessed successfully : xoyemi9795@datingel.com. Type: email_verification
2024-12-12 22:33:39,853 - db.py - global_logger - ERROR - Session rollback due to exception: 401: Not authenticated
2024-12-12 22:34:17,334 - db.py - global_logger - ERROR - Session rollback due to exception: 401: Not confirmed email
2024-12-12 22:34:34,536 - db.py - global_logger - ERROR - Session rollback due to exception: 401: Not confirmed email
2024-12-12 22:34:42,650 - db.py - global_logger - ERROR - Session rollback due to exception: 401: Not confirmed email
2024-12-12 22:35:52,975 - auth.py - global_logger - INFO - User xoyemi9795@datingel.com from database
2024-12-12 22:35:52,987 - users.py - global_logger - ERROR - Failed to update user's token: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: <coroutine object Auth.create_password_r... (expected str, got coroutine)
[SQL: UPDATE user_token SET refresh_token=$1::VARCHAR WHERE user_token.user_id = $2::INTEGER]
[parameters: (<coroutine object Auth.create_password_reset_token at 0x1045d9840>, 2)]
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-12-12 22:35:52,987 - db.py - global_logger - ERROR - Session rollback due to exception: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: <coroutine object Auth.create_password_r... (expected str, got coroutine)
[SQL: UPDATE user_token SET refresh_token=$1::VARCHAR WHERE user_token.user_id = $2::INTEGER]
[parameters: (<coroutine object Auth.create_password_reset_token at 0x1045d9840>, 2)]
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-12-12 22:39:18,228 - auth.py - global_logger - INFO - User xoyemi9795@datingel.com from cache
2024-12-12 22:39:18,278 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 22:39:18,283 - mail_publisher.py - global_logger - INFO - Message published to RabbitMQ with routing_key 'reset_password': {'email': 'xoyemi9795@datingel.com', 'username': 'string', 'host': 'http://127.0.0.1:8000/', 'type': 'reset_password', 'verification_token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ4b3llbWk5Nzk1QGRhdGluZ2VsLmNvbSIsImlhdCI6MTczNDAzNTk1OCwiZXhwIjoxNzM0MDM2MjU4fQ.WpbNI7zGR28uYIseIuCliVFkxJipLiOk7nmUBAjd9F0'}
2024-12-12 22:39:19,131 - rabbitmq_worker.py - global_logger - ERROR - Failed to process message: (550, 'Message subject: SPAM FOUND')
2024-12-12 22:41:55,155 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 22:41:55,162 - mail_publisher.py - global_logger - INFO - Message published to RabbitMQ with routing_key 'email_verification': {'email': 'xoyemi9795@datingel.com', 'username': 'string', 'host': 'http://127.0.0.1:8000/', 'type': 'email_verification', 'verification_token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ4b3llbWk5Nzk1QGRhdGluZ2VsLmNvbSIsImlhdCI6MTczNDAzNjExNSwiZXhwIjoxNzM0NjQwOTE1fQ.E_2z55zTzFUF13guZ_nfjpvumQKG1zVQm-18d_KjTT4'}
2024-12-12 22:41:56,363 - rabbitmq_worker.py - global_logger - INFO - Message precessed successfully : xoyemi9795@datingel.com. Type: email_verification
2024-12-12 22:42:27,740 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 22:42:27,745 - rabbitmq_worker.py - global_logger - INFO - Worker is consuming messages...
2024-12-12 22:42:43,059 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 22:42:43,065 - mail_publisher.py - global_logger - INFO - Message published to RabbitMQ with routing_key 'email_verification': {'email': 'xoyemi9795@datingel.com', 'username': 'string', 'host': 'http://127.0.0.1:8000/', 'type': 'email_verification', 'verification_token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ4b3llbWk5Nzk1QGRhdGluZ2VsLmNvbSIsImlhdCI6MTczNDAzNjE2MywiZXhwIjoxNzM0NjQwOTYzfQ.ZVirQo3yyHCFQmyzLXS1So-ieqCbfMb1PovtphZCZKc'}
2024-12-12 22:42:44,085 - rabbitmq_worker.py - global_logger - INFO - Message precessed successfully : xoyemi9795@datingel.com. Type: email_verification
2024-12-12 22:47:58,377 - conn_rabbitMQ.py - global_logger - INFO - Successfully connected to RabbitMQ
2024-12-12 22:47:58,382 - mail_publisher.py - global_logger - INFO - Message published to RabbitMQ with routing_key 'email_verification': {'email': 'xoyemi9795@datingel.com', 'username': 'string', 'host': 'http://127.0.0.1:8000/', 'type': 'email_verification', 'verification_token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ4b3llbWk5Nzk1QGRhdGluZ2VsLmNvbSIsImlhdCI6MTczNDAzNjQ3OCwiZXhwIjoxNzM0NjQxMjc4fQ.XFIoeUpJkJdLdwunItNgtZOtQStzDU78mccZ3g-d_7E'}
2024-12-12 22:47:59,241 - rabbitmq_worker.py - global_logger - INFO - Message precessed successfully : xoyemi9795@datingel.com. Type: email_verification
